apiVersion: v1
kind: ConfigMap
metadata:
  name: multitenant-alertmanager-config
data:
  multitenant_alertmanager.yaml: |
    listenaddr: 0.0.0.0:9093
    tracerurl: http://self-monitoring-alloy.self-monitoring.svc:4318
    alerts:
      alertmanagerUrl: "http://mimir-nginx.mimir.svc.cluster.local/alertmanager/api/v2"
      tenantlabel: "tenant"
      tenants:
      - "devops"
      - "app-development"
