apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitenant-alerts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multitenant-alerts
  template:
    metadata:
      labels:
        app: multitenant-alerts
    spec:
      containers:
      - name: multitenant-alerts
        image: pgillich/multitenant-alerts:v0.1.1
        command: ["/usr/local/bin/multitenant-alerts", "services", "multitenant-alerts", "--config", "/multitenant_alerts.yaml"]
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: config-volume
          mountPath: /multitenant_alerts.yaml
          subPath: multitenant_alerts.yaml
      volumes:
      - name: config-volume
        configMap:
          name: multitenant-alerts-config
