# https://pkg.go.dev/github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen#Configuration
package: api
generate:
  client: true
  chi-server: true
  models: true
  strict-server: true
output-options:
  include-operation-ids:
  - getAlerts
  - getSilences
  - getAlertGroups
# compatibility:
#   apply-chi-middleware-first-to-last: true
# output: pkg/api/alertmanager/gen.go
output: ../../pkg/api/alertmanager/chi.go
